status_map = {
    1: "New",
    2: "IT Assessment",
    3: "Development",
    4: "Code Review ",
    5: "SIT",
    6: "Training",
    7: "UAT",
    8: "Deployment",
    9: "Closed",
    10: "Rejected",
    11: "In Process",
    12: "Resolved",
    13: "Feedback",
}

priority_map = {1: "High", 2: "Medium", 3: "Low", 13: "Highest"}

tracker_map = {
    1: "Bug",
    2: "Change Request",
    3: "User consult",
    4: "IT enhamcement",
    5: "User training",
    6: "Research",
    7: "Milestone",
    8: "Support",
    9: "Production Control",
    10: "Production",
    11: "SCM",
}
user_map = {
    54: "Abril Cota",
    1: "Redmine Admin",
    67: "System Administrator",
    60: "Aeliana Shen",
    53: "Alan Hsieh",
    77: "Alberto De Loera",
    33: "Alena Guo",
    68: "Allen Lin",
    16: "Amy Wang",
    39: "Ann Lu",
    65: "Arys Zhang",
    32: "Carlos Rodriguez",
    75: "Christian Adame",
    43: "Christina Tsai",
    7: "David Tseng",
    35: "Dicky Chang",
    41: "Erik Nguyen",
    23: "Ethan Hsiao",
    17: "Feng Shang",
    62: "Fernando Saenz",
    28: "Gary Pan",
    64: "Giovanni Nuño",
    73: "Hao Zhang",
    6: "Hilda Hernandez",
    70: "Honfeng Lu",
    26: "Hongwei Qi",
    69: "Hugo Perea",
    49: "Ian Lin",
    22: "Jennifer Jiang",
    34: "Jennifer Wang",
    74: "Jesus Jafet  Saiz Guevara",
    56: "Jolin Chen",
    52: "Jonathan Lee",
    5: "Jorge Maciel",
    9: "Jose Andujar",
    10: "Julian Leung",
    27: "Julia Sung",
    38: "Kristal Divitku",
    40: "Lina Wirahadi",
    51: "May Hsueh",
    46: "Min Cheng",
    63: "Moises Ontiveros",
    44: "Neil Chen",
    37: "Nhat Do",
    55: "Nick Chen",
    19: "Niko Zhao",
    78: "Norah Xu",
    36: "Peiyuan Li",
    45: "Pelly Chen",
    71: "Rain Lopez",
    24: "Romee Ou",
    21: "Ryder Liang",
    59: "Sara Su",
    25: "Smallthi Chang",
    29: "Tomas Lopez",
    72: "Tomas Lopez",
    66: "demo user",
    48: "Victor Cabrera",
    58: "Vivian Tsou",
    30: "Yifei Shi",
    76: "Yitong Wu",
    20: "Zaawar Ejaz",
    18: "Zach Novak",
    31: "Zach Quinn",
}
